/**
 * Error codes for the application
 */
export const ErrorCodes = {
  // API errors
  API_ERROR: 'API_ERROR',
  API_KEY_ERROR: 'API_KEY_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',

  // File system errors
  FILE_SYSTEM_ERROR: 'FILE_SYSTEM_ERROR',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Tagging errors
  TAGGING_ERROR: 'TAGGING_ERROR',
  EMPTY_CONTENT: 'EMPTY_CONTENT',
  INVALID_TAXONOMY: 'INVALID_TAXONOMY',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',

  // Markdown errors
  MARKDOWN_ERROR: 'MARKDOWN_ERROR',
  FRONTMATTER_PARSE_ERROR: 'FRONTMATTER_PARSE_ERROR',
  FRONTMATTER_UPDATE_ERROR: 'FRONTMATTER_UPDATE_ERROR',

  // Configuration errors
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  MISSING_API_KEY: 'MISSING_API_KEY',
  INVALID_MODEL: 'INVALID_MODEL',
  COST_LIMIT_ERROR: 'COST_LIMIT_ERROR',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Generic errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
