name: VS Code Extension CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/vscode/**'
      - 'packages/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/vscode/**'
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: |
          cd apps/vscode
          pnpm run build
          
      - name: Test
        run: |
          cd apps/vscode
          pnpm run test

  bundle-analysis:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: |
          cd apps/vscode
          pnpm run build
      
      - name: Analyze Bundle Size
        run: |
          npx source-map-explorer apps/vscode/dist/extension.js --html vscode-bundle-analysis.html
      
      - name: Upload Bundle Analysis
        uses: actions/upload-artifact@v4
        with:
          name: vscode-bundle-analysis
          path: vscode-bundle-analysis.html

  package:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: |
          cd apps/vscode
          pnpm run build
      
      - name: Package Extension
        run: |
          cd apps/vscode
          pnpm run package
      
      - name: Upload VSIX Package
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: apps/vscode/*.vsix 