name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build plugin
        run: pnpm run build
      
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          echo "Creating release for tag: $tag"
          
          # Create archive of the plugin
          cd apps/obsidian-plugin/dist
          zip -r obsidian-magic-$tag.zip main.js manifest.json styles.css
          
          # Create GitHub release
          gh release create "$tag" \
            --title "Obsidian Magic v$tag" \
            --notes "See the [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details." \
            obsidian-magic-$tag.zip
