name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build all packages
        run: pnpm run build
      
      - name: Package Obsidian plugin
        run: |
          cd apps/obsidian-plugin
          pnpm run package
          
      - name: Package VS Code extension
        run: |
          cd apps/vscode
          pnpm run package
          
      - name: Package CLI tool
        run: |
          cd apps/cli
          pnpm pack
      
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          echo "Creating release for tag: $tag"
          
          # Create archive of the Obsidian plugin
          cd apps/obsidian-plugin/release
          zip -r obsidian-magic-plugin-$tag.zip .
          
          # Find VS Code extension package
          vsix_file=$(find ../vscode -name "*.vsix" | head -n 1)
          
          # Find CLI package
          tgz_file=$(find ../cli -name "*.tgz" | head -n 1)
          
          # Create GitHub release
          gh release create "$tag" \
            --title "Obsidian Magic v$tag" \
            --notes "See the [CHANGELOG](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details." \
            obsidian-magic-plugin-$tag.zip $vsix_file $tgz_file
